version: '3.7'

services:
  projectx-identity:
    image: projectx-identity:latest
    build:
      context: ..\
      dockerfile: Services\ProjectX.Identity\ProjectX.Identity.API\Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      - 5000:5000 # This is for debugging, we can reach our services through NGINX
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5000
      - JAEGER_HOST=projectx-jaeger
      - JAEGER_PORT=6831
      - SEQ_URI=http://projectx-seq:5341

  projectx-dashboard:
    image: projectx-dashboard:latest
    build:
      context: ..\
      dockerfile: Services\ProjectX.Dashboard\ProjectX.Dashboard.API\Dockerfile
    restart: on-failure
    networks:
      - projectx 
    ports:
      - 5001:5001 # This is for debugging, we can reach our services through NGINX
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - JAEGER_HOST=projectx-jaeger
      - JAEGER_PORT=6831
      - SEQ_URI=http://projectx-seq:5341

networks:
  projectx:
    name: projectx-network
    external: true