kind: ConfigMap
apiVersion: v1
metadata:
  name: identity-cm
  labels:
    app: project-x
    service: identity
data:
  ASPNETCORE_ENVIRONMENT: Development
  ASPNETCORE_URLS: http://0.0.0.0:80
  ConnectionStrings__DbConnection: Host=sqldata;Database=ProjectX.Identity;Username=postgres;Password=root