kind: Deployment
apiVersion: apps/v1
metadata:
  name: filestorage
  labels:
    app: project-x
    service: filestorage
spec:
  replicas: 1
  selector:
    matchLabels:
      service: filestorage
  template:
    metadata:
      labels:
        app: project-x
        service: filestorage
    spec:
      containers:
        - name: filestorage-api
          image: andriy1024/projectx-filestorage:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
            # - containerPort: 81
            #   protocol: TCP
          livenessProbe:
            httpGet:
              port: 80
              path: /liveness
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              port: 80
              path: /hc
            initialDelaySeconds: 10
            periodSeconds: 30
            timeoutSeconds: 5
          envFrom:
            - configMapRef:
                name: filestorage-cm
