name: Build ProjectX

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build back-end Projects
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
          
      - name: Build the Docker image
        run: docker build -f ./backend/Services/ProjectX.Dashboard/ProjectX.Dashboard.API/Dockerfile --force-rm -t andriy1024/projectx-dashboard:latest ./backend
        
      - name: Push the Docker image
        run: docker login -u andriy1024 -p ${{ secrets.DOCKER_TOKEN }} && docker push andriy1024/projectx-dashboard:latest
        
